feat: add exasol input mapping
keboola/input-mapping pull request #105
Opened 2021-08-21 14:46 UTC by odinuv

2021-08-23 06:22 UTC, joker806 requested changes
To dedeni `Exasol extends Snowflake` se mi teda nelibi. Jinak v pohode.

2021-08-23 06:22 UTC, joker806 commented on src/Table/Strategy/Exasol.php
> +class Exasol extends Snowflake
Hmm.. nejsem si uplne jistej, ze tohle je zdravy. Chapu, ze treba ty strategie sdili hodne spolecneho a tak je jednoduchy to podedit, ale kdyby ti nekdo misto `Snowflake` strategie soupnul `Exasol`, nebudes happy.

Vidim, ze `Redshift` to ma stejne. Pokud to sdili stejne veci a chceme se drzet dedicnosti, nedaval by smysl treba `AbstractStrategy` -> `AbstractSqlStrategy` -> `Exasol`?

2021-08-23 06:53 UTC, odinuv commented on src/Table/Strategy/Exasol.php
> +class Exasol extends Snowflake
Jasně, udělal jsem to zbytečně zbrkle, jdu se k tomu vrátit

2021-08-24 09:30 UTC, joker806 approved these changes
Cekal jsem, ze bude vic rozdilu.. ale takle se mi to libi :)

2021-08-24 11:57 UTC, merged